### PR TITLE
Better backward compatibility

### PR DESCRIPTION
**Pull request by kwesolowski**
Minor thing that was spamming my debug window

### CODE REVIEW

**Comment by Hypnos3** [comment]
Thank You!

I'm currently developing with a beta version in the dev branch. I will merge that with it and then publish it with the new version. Therefore it will take a while.

**Comment by Hypnos3** [comment]
As I already see, the
```send = send || this.send;```
is already changed to
```send = send || function (...args) { node.send.apply(node, args); };```

this should be similar to
```send = send || function() { node.send.apply(node, arguments) };```

This is already in the published version 0.4.10.  Unfortunately, I forgot to merge this into the master branch.

**Comment by kwesolowski** [comment]
Assuming i am bug tolerant and playing on node 0.20.7 should I use dev branch? Or is it "really dev"?:)

**Comment by Hypnos3** [comment]
You can use the dev branch. It seems to be stable enough that I will publish this in the next days.

**Pull request merged**
